### ISSUE TITLE
Is there a way to set --target-dir with dice?

### ISSUE THREAD

**Issue by abalage** [SUSE/dice#11]
Apparently all build processes takes place in /tmp which is very limited in size in my case.
I see that kiwi supports --target-dir but I am not sure how it can be used to override the default /tmp?

I was also thinking of using .kiwirc but it looks like that file is missing in kiwi-ng.

**Comment by abalage** [comment]
Is my assumption right about that this /tmp is actually within the docker image?
Because in that case my size limit is not on /tmp but on /var/lib/docker ..

**Comment by abalage** [comment]
Okay, the workaround I used is to use a Vagrant file and mount a host dir into /tmp.

I still ran into issues with lvcreate. Apparently my problem is not about disk space.
Sorry about the noise, this case can be closed.

**Comment by schaefi** [comment]
Probably a problem with the lvmetad. I will disable the use of the lvm metadata daemon for images in the container. It's just a guess but maybe it fixes the lvm problems you have

**Comment by abalage** [comment]
If it gives anything useful then here it is what I have.

```
[ ERROR   ]: 13:51:25 | KiwiCommandError: lvcreate: stderr:   /dev/systemVG/root: not found: device not cleared
  Aborting. Failed to wipe start of new LV.
, stdout: (no output on stdout)
```
I am happy to test any release.
