### ISSUE TITLE
cleanup fails with 'Operation not permitted' on a Leap 42.1 VM

### ISSUE THREAD

**Issue by abalage** [SUSE/dice#14]
This is what I got when the buildhost is a Leap 42.1 in Virtualbox
If I use Docker as a buildhost, it works fine.

```
$ dice build .
[6887][centos7]: BuildSystem: Setting up host buildsystem for: 192.168.33.10
[6887][centos7]: Solver: Running package solver
[6887][centos7]: HostBuildSystem: Using buildsystem 192.168.33.10 for /home/balage/kiwi/blindspotter/centos7...
[6887][centos7]: HostBuildSystem: Provision build system...
[6887][centos7]: HostBuildSystem: sending incremental file list
[6887][centos7]:
[6887][centos7]: sent 705 bytes  received 22 bytes  1,454.00 bytes/sec
[6887][centos7]: total size is 7,997,139  speedup is 11,000.19
[6887][centos7]:
[6887][centos7]: Job: Preparing build...
[6887][centos7]: Job: Building...
[6887][centos7]: Job: Bundle results...
[6887][centos7]: Job: Retrieving results in /home/balage/kiwi/blindspotter/centos7/.dice/build_results.tar...
[6887][centos7]: Job: Cleanup build...
[6887][centos7]: Job: Cleanup failed with: rm: ”/tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root/var/lib/machines” nem törölhető: A művelet nem engedélyezett
[6887][centos7]: rm: ”/tmp/kiwi_build_20161207-6887-cylmbw.dice/kiwi_boot_root.c1qoxae0/var/lib/machines” nem törölhető: A művelet nem engedélyezett
[6887][centos7]:
[6887][centos7]: HostBuildSystem: Stopping build process on 192.168.33.10...
[6887][centos7]: Reset working directory
```

Translation HU->ENG:
'nem törölhető: A művelet nem engedélyezett' -> 'cannot be deleted: Operation not permitted'

The files indeed cannot be removed, even manually.

```
vagrant-openSUSE-Leap:/home/vagrant # cd /tmp/
vagrant-openSUSE-Leap:/tmp # ls -la
total 4
drwxrwxrwt 1 root    root  654 Dec  7 15:36 .
drwxr-xr-x 1 root    root  180 Mar 31  2016 ..
drwxrwxrwt 1 root    root    0 Mar 31  2016 .ICE-unix
drwxrwxrwt 1 root    root    0 Mar 31  2016 .Test-unix
drwxrwxrwt 1 root    root    0 Mar 31  2016 .X11-unix
drwxrwxrwt 1 root    root    0 Mar 31  2016 .XIM-unix
drwxrwxrwt 1 root    root    0 Mar 31  2016 .font-unix
drwxr-xr-x 1 root    root   56 Dec  2 14:10 aa
drwxr-xr-x 1 root    root   56 Dec  2 14:31 bb
drwxr-xr-x 1 root    root   56 Dec  2 14:40 c
drwx------ 1 root    root    0 Dec  2 14:40 d
-rw-r--r-- 1 root    root   42 Mar 31  2016 dracut_failed_drivers
drwxr-xr-x 1 root    root  314 Dec  6 13:54 kiwi_boot_root_copy.0_9ue0f0
drwxr-xr-x 1 root    root  314 Dec  7 13:29 kiwi_boot_root_copy.7b0316c7
drwxr-xr-x 1 root    root   56 Dec  2 15:01 kiwi_build_20161202-13111-eb2kbw.dice
drwxr-xr-x 1 root    root   56 Dec  2 14:54 kiwi_build_20161202-9938-p7gmod.dice
drwxr-xr-x 1 root    root   56 Dec  5 10:34 kiwi_build_20161205-11312-j93f57.dice
drwxr-xr-x 1 root    root  512 Dec  6 13:57 kiwi_build_20161206-28885-cbmzhp.dice
drwxr-xr-x 1 root    root   56 Dec  7 13:32 kiwi_build_20161207-6887-cylmbw.dice
drwx------ 1 vagrant users  20 Mar 31  2016 ssh-oFxOinztYW
vagrant-openSUSE-Leap:/tmp # ls -la /tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root/var/lib/machines
total 0
drwx------  1 root root  0 Dec  7 13:25 .
drwxr-xr-x. 1 root root 16 Dec  7 13:32 ..
vagrant-openSUSE-Leap:/tmp # stat /tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root/var/lib/machines
  File: ‘/tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root/var/lib/machines’
  Size: 0               Blocks: 0          IO Block: 4096   directory
Device: 2ah/42d Inode: 256         Links: 1
Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-12-07 13:29:22.499125936 +0100
Modify: 2016-12-07 13:25:35.893879935 +0100
Change: 2016-12-07 13:25:35.893879935 +0100
 Birth: -
vagrant-openSUSE-Leap:/tmp # rm -rf /tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root/var/lib/machines
rm: cannot remove ‘/tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root/var/lib/machines’: Operation not permitted
vagrant-openSUSE-Leap:/tmp # lsof +D /tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root/var/lib/machines
vagrant-openSUSE-Leap:/tmp # dmesg | tail
[  424.600706] systemd-tmpfiles[19325]: Failed to parse ACL "group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
[  424.600757] systemd-tmpfiles[19325]: Failed to parse ACL "d:group:adm:r-x,d:group:wheel:r-x": Invalid argument. Ignoring
[  424.600775] systemd-tmpfiles[19325]: Failed to parse ACL "group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
[  533.456884] loop: module loaded
[  536.212496] EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: (null)
[  536.238256] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: (null)
[  657.020457] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
[  669.419133] EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: (null)
[  669.444167] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
[  669.463847] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: (null)
vagrant-openSUSE-Leap:/tmp # dmesg -T | tail
[Wed Dec  7 13:27:42 2016] systemd-tmpfiles[19325]: Failed to parse ACL "group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
[Wed Dec  7 13:27:42 2016] systemd-tmpfiles[19325]: Failed to parse ACL "d:group:adm:r-x,d:group:wheel:r-x": Invalid argument. Ignoring
[Wed Dec  7 13:27:42 2016] systemd-tmpfiles[19325]: Failed to parse ACL "group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
[Wed Dec  7 13:29:31 2016] loop: module loaded
[Wed Dec  7 13:29:34 2016] EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: (null)
[Wed Dec  7 13:29:34 2016] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: (null)
[Wed Dec  7 13:31:35 2016] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
[Wed Dec  7 13:31:47 2016] EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: (null)
[Wed Dec  7 13:31:47 2016] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
[Wed Dec  7 13:31:47 2016] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: (null)
```

Relevant part from build.log but I am attaching it anyway.
```
[ INFO    ]: 13:31:55 | Cleaning up BootImageKiwi instance
[ DEBUG   ]: 13:31:55 | EXEC: [rm -r -f /tmp/kiwi_build_20161207-6887-cylmbw.dice/kiwi_boot_root.c1qoxae0]
[ DEBUG   ]: 13:31:55 | EXEC: Failed with stderr: rm: cannot remove ‘/tmp/kiwi_build_20161207-6887-cylmbw.dice/kiwi_boot_root.c1qoxae0/var/lib/machines’: Operation not permitted
, stdout: (no output on stdout)
[ INFO    ]: 13:31:55 | Cleaning up VolumeManagerLVM instance
[ DEBUG   ]: 13:31:55 | EXEC: [mountpoint /tmp/kiwi_volumes.sd2xsc8u//var]
[ DEBUG   ]: 13:31:55 | EXEC: [mountpoint /tmp/kiwi_volumes.sd2xsc8u]
[ DEBUG   ]: 13:31:55 | EXEC: [rm -r -f /tmp/kiwi_volumes.sd2xsc8u]
[ DEBUG   ]: 13:31:55 | EXEC: [vgchange -an systemVG]
[ INFO    ]: 13:31:55 | Cleaning up FileSystemExt4 instance
[ DEBUG   ]: 13:31:55 | EXEC: [mountpoint /tmp/kiwi_mount_manager.4gmncccc]
[ DEBUG   ]: 13:31:55 | EXEC: [mountpoint /tmp/kiwi_mount_manager.4gmncccc]
[ DEBUG   ]: 13:31:55 | EXEC: [rm -r -f /tmp/kiwi_mount_manager.4gmncccc]
[ INFO    ]: 13:31:55 | Cleaning up Disk instance
[ DEBUG   ]: 13:31:55 | EXEC: [kpartx -s -d /dev/loop0]
[ INFO    ]: 13:31:55 | Cleaning up LoopDevice instance
[ DEBUG   ]: 13:31:55 | EXEC: [losetup -d /dev/loop0]
[ INFO    ]: 13:31:55 | Creating vmdk Disk Format
[ DEBUG   ]: 13:31:55 | EXEC: [qemu-img convert -f raw /tmp/kiwi_build_20161207-6887-cylmbw.dice/LimeJeOS-CentOS-07.0.x86_64-1.2.0.raw -O vmdk -o adapter_type=buslogic /tmp/kiwi_build_20161207-6887-cylmbw.dice/LimeJeOS-CentOS-07.0.x86_64-1.2.0.vmdk]
[ WARNING ]: 13:32:01 | Could not find vmtoolsd in image root /tmp/kiwi_build_20161207-6887-cylmbw.dice/build/image-root
[ WARNING ]: 13:32:01 | Update of VMDK metadata skipped
[ INFO    ]: 13:32:01 | Cleaning up BootImageKiwi instance
[ DEBUG   ]: 13:32:01 | EXEC: [rm -r -f /tmp/kiwi_build_20161207-6887-cylmbw.dice/kiwi_boot_root.5pmr27ss]
[ INFO    ]: 13:32:01 | Cleaning up BootImageKiwi instance
[ DEBUG   ]: 13:32:01 | EXEC: [rm -r -f /tmp/kiwi_build_20161207-6887-cylmbw.dice/kiwi_boot_root.z1n_rj5c]
[ INFO    ]: 13:32:01 | Result files:
[ INFO    ]: 13:32:01 | --> disk_format_image: /tmp/kiwi_build_20161207-6887-cylmbw.dice/LimeJeOS-CentOS-07.0.x86_64-1.2.0.vmdk
[ INFO    ]: 13:32:01 | --> disk_format_machine_settings: /tmp/kiwi_build_20161207-6887-cylmbw.dice/LimeJeOS-CentOS-07.0.x86_64-1.2.0.vmx
[ INFO    ]: 13:32:01 | --> disk_image: /tmp/kiwi_build_20161207-6887-cylmbw.dice/LimeJeOS-CentOS-07.0.x86_64-1.2.0.raw
[ INFO    ]: 13:32:01 | --> image_packages: /tmp/kiwi_build_20161207-6887-cylmbw.dice/LimeJeOS-CentOS-07.0.x86_64-1.2.0.packages
[ INFO    ]: 13:32:01 | --> image_verified: /tmp/kiwi_build_20161207-6887-cylmbw.dice/LimeJeOS-CentOS-07.0.x86_64-1.2.0.verified
[ INFO    ]: 13:32:01 | Cleaning up BootImageKiwi instance
[ DEBUG   ]: 13:32:01 | EXEC: [rm -r -f /tmp/kiwi_build_20161207-6887-cylmbw.dice/kiwi_boot_root.oix0awlx]
Exception ignored in: <bound method BootImageKiwi.__del__ of <kiwi.boot.image.kiwi.BootImageKiwi object at 0x7fa6bab45630>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/kiwi/boot/image/base.py", line 282, in __del__
    Path.wipe(directory)
  File "/usr/lib/python3.4/site-packages/kiwi/path.py", line 75, in wipe
    ['rm', '-r', '-f', path]
  File "/usr/lib/python3.4/site-packages/kiwi/command.py", line 106, in run
    command[0], error.decode(), output.decode()
kiwi.exceptions.KiwiCommandError: rm: stderr: rm: cannot remove ‘/tmp/kiwi_build_20161207-6887-cylmbw.dice/kiwi_boot_root.c1qoxae0/var/lib/machines’: Operation not permitted
, stdout: (no output on stdout)
[ INFO    ]: 13:32:05 | Bundle build results from /tmp/kiwi_build_20161207-6887-cylmbw.dice
```
I am attaching config.xml, Dicefile and the Vagrantfile from my tests.

[Vagrantfile.txt](https://github.com/SUSE/dice/files/636928/Vagrantfile.txt)
[Dicefile.txt](https://github.com/SUSE/dice/files/636925/Dicefile.txt)
[config.xml.txt](https://github.com/SUSE/dice/files/636927/config.xml.txt)
[build.log.txt](https://github.com/SUSE/dice/files/636926/build.log.txt)

Version details:
Dice: 0.7.10 running on Leap 42.2 (host)
Kiwi: 8.27.2 running in Leap 42.1 (VirtualBox VM)
VirtualBox: 5.1.8 running on Leap 42.2 (host)

This is not a showstopper as I can build by using Docker.

**Comment by abalage** [comment]
Vagrant box is from here: https://atlas.hashicorp.com/opensuse/boxes/openSUSE-42.1-x86_64

**Comment by schaefi** [comment]
Thanks for the translation, I would have been lost without it 😄 

I noted that building CentOS (I guess with RHEL would be the same) under my platform always creates a subvolume in '<image-root>/var/lib/machines' which is not cleaned or deleted, thus 'rm' command refuses to delete that folder. I have the strong impression this is nothing related to KIWI, but to a CentOS systemd miss-function, as I think during the systemd installation detects that my host is running 'btrfs' and auto creates that volume and then it stays there forever.

Does this apply to your environment too ? Unfortunately this is not something we can fix

In a docker container there is no systemd, thus you won't see that issue there

**Comment by abalage** [comment]
Yes indeed the VM host uses btrfs.

I do not know the internals of Kiwi, but how could an optional host parameter (btrfs, etc) implicitly affect the build which according to my understanding should have been somehow isolated from the host?

p.s.: Let me create another VM but instead of btrfs I am going to use another filesystem.

**Comment by schaefi** [comment]
if you are using a real VM which is the case here iirc the filesystem on the host running the VM should not matter. The VM and the host are completely isolated when running a virtual machine. Using containers like docker shares more with the host e.g the kernel and parts of the filesystem... but is then also faster

My guess is that the box you used with vagrant, I mean the datat from https://atlas.hashicorp.com/opensuse/boxes/openSUSE-42.1-x86_64 is configured to use btrfs. Could that be the case ? meaning the VM itself uses btrfs and the build then runs in an environment where it can see the btrfs

I would say changing the host fs must not have any effect

**Comment by schaefi** [comment]
The reason for using dice is exactly this isolation. Using a VM is the most secure way to do it, but also the slowest because the VM needs to boot before it actually can do something, also I/O between VM and host is a bottle neck.

With containers the isolation from the host is weaker, but build speed matters and so it depends on the use case what is best

**Comment by schaefi** [comment]
JFI: I will work on this part in the next weeks: https://github.com/SUSE/kiwi/issues/15

once that is done I'm going to build a vagrant vm for the libvirt provider so that we can provide both a docker build container and for complete isolation a VM for libvirt. If that is done you don't need to use "some" vagrant box but can use the one we provide and do our testing with.

I'll keep you posted

**Comment by abalage** [comment]
> I would say changing the host fs must not have any effect

Sorry, on the host in this context I meant the OS of the buildhost which in my case was a Vagrant VM running on btrfs.
Meanwhile I created another Leap 42.1 VM but on ext4 instead of btrfs and ran the same build on it.
It worked fine.
My question about separation was targeting this use case. 

If the build does not work in cases when a buildhost does have btrfs, but works ie. with ext4 then I consider it as a bug.
What do you think?

**Comment by schaefi** [comment]
In the long run you just tell dice what to build and where to build it, and it just builds in an environment
we know and we provide and control and where we can eliminate such effects like the one reported here

**Comment by schaefi** [comment]
for docker this is already in place, meaning kiwi just pulls from dockerhub a container where we know it has everything required to build the image. For other build platforms like vagrant with libvirt or virtualbox no automatism exists. For the public cloud there is an aws build ami but it's still private to my account.

All that just as little bit of background what my goals with dice are

**Comment by abalage** [comment]
Thanks Marcus for the detailed clarification. 
Yes all makes sense, except this one which gives me the feeling that either some nasty thing is going on with systemd or the separation is not complete.

> If the machine which runs kiwi uses itself a btrfs you run into trouble when kiwi has to install the systemd package because it interferes with the running systemd and the active btrfs. 

You may call me paranoid. :)

Of course I can go along with you regarding providing build environments which works out of the box for the very same reason why I originally did not want to hassle about creating one.

I am looking forward for trying out the improvements you planned.
This ticket can be closed.

**Comment by schaefi** [comment]
of course you are right regarding what happens on the systemd side of things. I think it would be good to report the behavior on the systemd mailing list. Actually it could be reproduce by just installing the systemd package inside of a chroot while the currently active system has a btrfs root fs. You will see the creation of a /var/lib/machines subvolume for whatever reason.

We don't see this with the suse systemd package but it applies to the CentOS version and maybe also to rhel (haven't looked at that one)

I'll close the report once I have a vagrant box build ready

Thanks

**Comment by schaefi** [comment]
HI

The vagrant box for kiwi builds is now available and I have update the documentation here.

* http://suse.github.io/kiwi/container_builder.html#the-vagrant-setup-for-the-libvirt-provider

It would be great if you can give it a try if your time permits this

Thanks much and happy X-mas 😄

**Comment by abalage** [comment]
Hi!

Thanks for the update.
It sounds interesting but probably I will only have time next year to try it out. 

Frohe Weihnachten! :)

**Comment by schaefi** [comment]
Hi,

>    Frohe Weihnachten! :)

:-) sure, Frohe Weihnachten :-)
