### ISSUE TITLE
build for Leap 15

### ISSUE THREAD

**Issue by druonysus** [SUSE/dice#17]
[here](https://download.opensuse.org/repositories/Virtualization:/Appliances:/ContainerBuilder/) you can see there is no Leap 15 repo. It would be great to have OBS build this for Leap 15 too

**Comment by schaefi** [comment]
done:

* https://build.opensuse.org/project/show/Virtualization:Appliances:ContainerBuilder

Please note, due to other tasks I didn't hat the time to actively test dice on Leap15. This is basically a side project of mine which gets attention when I stumble over issues while using it :)

Thanks

**Comment by druonysus** [comment]
noted. thank you for adding it. I will add the repo and see how it goes. :smiley:
