### ISSUE TITLE
Pass kiwi parameters to build process

### ISSUE THREAD

**Issue by Thomas9999** [SUSE/dice#6]
The current dice build process runs kiwi with fixed parameters. Sometimes it's necessary to pass additionall values (e.g. --add-profile for different builds). There is no way to do it today.

A pre-kiwi hook of some sort would also be interesting. In our environment we sometimes manipulate the config.xml before running kiwi:
svn update
REVISION=`svn info | grep Revision | sed "s/Revision: //"`
echo "Build no: "$REVISION > root/etc/hp-release
echo "Build date: `date`" >> root/etc/hp-release
sh -c 'xsltproc --stringparam name_update SAP-Application-legacy rename.xsl masterconfig.xml > config.xml
<run kiwi>

**Comment by schaefi** [comment]
With regards to pre-kiwi hooks you can use a vagrant provision script. Read more about it here
http://docs.vagrantup.com/v2/provisioning/shell.html

The kiwi image description in the container is available below /vagrant

**Comment by schaefi** [comment]
I'm going to add support for passing --add-profile next

btw, there is already support to pass --kiwitype
