### ISSUE TITLE
repomd: undefined method `parse' for URI:Module

### ISSUE THREAD

**Issue by abalage** [SUSE/dice#9]
Hello,

I am trying to use dice as described here: https://suse.github.io/kiwi/container_builder.html
I am on OpenSUSE 42.2. The version I have in official repository is 0.7.3.

I am trying to build a CentOS 7 image which is based on the one shipped in https://github.com/SUSE/kiwi-descriptions

I am running into this:
`
$ dice build blindspotter/centos7
[22481][centos7]: BuildSystem: Setting up Docker buildsystem
[22481][centos7]: Solver: Running package solver
[22481][centos7]: Downloading file: http://mirror.centos.org/centos/7/os/x86_64/repodata/repomd.xml failed: undefined method `parse' for URI:Module
[22481][centos7]: DockerBuildSystem: Delete container...
[22481][centos7]: Reset working directory
$
`

Ps. I tried to use more recent version of dice as https://github.com/SUSE/dice#installation suggests, but there is no such dice in that mentioned repo, however I could find another repo with similar name (http://download.opensuse.org/repositories/Virtualization:/Appliances:/ContainerBuilder/) but there is no variant for 42.2.

Can you give me some suggestions where to go from here?

**Comment by schaefi** [comment]
> failed: undefined method parse' for URI:Module

I remember that I had a similar problem in the past, the URI module from ruby provides a parse method but if something overwrites the URI namespace it can't be found anymore.

As you already found out I had not build a dice package for 42.2, from your report it was not clear to me how you have installed dice on 42.2. Let me assume the reason for the trouble is that missing package for 42.2 for the moment :) I have added the 42.2 build target and you now can install the package build for that distro. In the best case this fixes your issue, if not we need to debug deeper

Thanks for the hint to the wrong installation information. I have update the README too

Hope that helps

**Comment by abalage** [comment]
> from your report it was not clear to me how you have installed dice on 42.2. 
I have installed it from repo-oss repositories of 42.2 (http://download.opensuse.org/distribution/leap/42.2/repo/oss/)

> I have added the 42.2 build target and you now can install the package build for that distro. In the best case this fixes your issue, if not we need to debug deeper.
Thanks. Indeed it seems like the upgrade fixed the issue. Now I have different issues but I may file another github issue for that.

Thank you very much for your quick help.

**Comment by schaefi** [comment]
ok one down some more to go 😄 

I'll close this one, let me know if I can help with the other issues
